<?php
/**
 * Created by IntelliJ IDEA.
 * User: Sven
 * Date: 23.10.12
 * Time: 21:23
 * To change this template use File | Settings | File Templates.
 */
?>
<div id="topbar" style="width: 100%;height:15%;background-color: gray;">
    <div id="logo" style="float:left;width: 30%;height: 100%"> LOGO</div>
    <div id="buttonbar" style="float: left;margin-left: 20%;width: 50%;height: 100%">
        <div id="btn1" style="float:left;">BTN1</div>
        <div id="btn2" style="float:left;">BTN2</div>
        <div id="btn3" style="float:left;">BTN3</div>
    </div>
</div>