<?php
/**
 * Created by IntelliJ IDEA.
 * User: Sven
 * Date: 23.10.12
 * Time: 21:42
 * To change this template use File | Settings | File Templates.
 */
?>

<div id="leftbar" style="float:left;width: 25%;height:85%;background-color: #7fffd4;">
        <div id="menu_entry1"> Produkte A</div>
    <div id="menu_entry2"> Produkte B</div>
    <div id="menu_entry3"> Produkte C</div>
</div>